### PR TITLE
Update recipes/ssl.rb to use OpenSSL Cookbook

### PR DESCRIPTION
**Pull request by charlesjohnson**
- Add dependency on openssl cookbook to metadata.rb
- Rebuilt Berksfile.lock solution
- Remove ['supermarket']['ssl']['openssl_bin'] attribute
- Update ssl.rb to use openssl cookbook to generate certs & dhparam
- Update ssh_spec.rb to correctly validate ssl.rb resource set
- Update ssl_spec.rb so it catches that ssl disable should take precedence in behavior over supplied certificate
- Fix ssl.rb so that ssl disable takes precedence over supplied certificate
- Refactor ssl_spec.rb to use shared example sets

### CODE REVIEW

**Comment by charlesjohnson** [comment]
Note: I looked at the Kitchen tests but they appear to be non-functional when I try to run them, so I didn't dig into them. If I missed something, happy to expand Kitchen test coverage too.

**Comment by smith** [comment]
Not sure where it's coming from, but on every spec I'm getting:

```
Failure/Error: runner.converge(described_recipe)
NoMethodError:
  undefined method `provides' for WindowsSdkCookbook::Provider:Class
```

Using the bundler-based instructions from the cookbook README.

If I use ChefDK (`chef exec rspec`) I get only 2 failures related to postgres stubs, and a bunch of deprecation warnings.

Are you seeing either of these when you run the specs?

I'm downloading a nightly to try running this on a real machine to double-check if everything works.

The code looks great though! I'll let you know if I figure anything else out.

**Comment by smith** [comment]
Oh, and if I `bundle exec rspec` on master I get the same results as doing `chef exec rspec`.

**Comment by smith** [comment]
Got this to work in test kitchen. :+1: once the specs are fixed.

**Comment by charlesjohnson** [comment]
Ah, the Gemfile was behind what shipped in ChefDK 0.8, and I was using 'chef exec rspec.' Should be fine now.

Note that the database_spec was broken when I got here and it's resisting my attempts to fix it, so I just left it.

**Comment by smith** [comment]
:+1: looks good

**Pull request merged**
