### PR TITLE
Nginx ssl

### PR DESCRIPTION
**Pull request by kirtfitzpatrick**

### CODE REVIEW

**Comment by nellshamrell** [comment]
Looks like the builds failed.

**Comment by nellshamrell** [comment]
Still looks like the build is failing.  Once that is fixed, I think this is good to go.

**Comment by nellshamrell** [comment]
Additionally, this is potentially a breaking change.  Even though the default attribute is set to true, it won't overwrite the defaults of an existing Supermarket installation.  I think this should be released as 2.0.0

**Comment by kirtfitzpatrick** [comment]
@nellshamrell The build will never pass. Travis is not configured yet.

**Comment by nellshamrell** [comment]
:+1:

**Comment by nellshamrell** [comment]
:+1: Let's release this as supermarket 2.0

**Pull request merged**
