### PR TITLE
adds supermarket-ctl command to directly enter rails console

### PR DESCRIPTION
**Pull request by nellshamrell**
Fixes chef/supermarket#885

### CODE REVIEW

**Comment by robbkidd** [comment]
Thoughts on having the console run as the `supermarket` service account that the rails app runs as?

`s/sudo/sudo -u supermarket/`

**Comment by nellshamrell** [comment]
Sounds good to me!  Will add that in on Mon :)

**Comment by nellshamrell** [comment]
Done!

**Comment by robbkidd** [comment]
:100:

**Pull request merged**
