### PR TITLE
Ensure sitemap files exist with permissions 

### PR DESCRIPTION
**Pull request by robbkidd**
Allows Sidekiq worker running as service account to update sitemap.

### CODE REVIEW

**Comment by nellshamrell** [comment]
This looks fine to me.

**Comment by robbkidd** [comment]
I am working on confirming that these file resources with no content act like touches.

**Comment by nathenharvey** [comment]
:+1:

**Comment by robbkidd** [comment]
Doubly-confirmed. :+1:

**Comment by robbkidd** [comment]
And apparently production community site has a config for _two_ sitemaps, so ...

```
Permission denied @ rb_sysopen - /opt/supermarket/embedded/service/supermarket/public/sitemap2.xml.gz
```

Argh!

**Pull request merged**
