### PR TITLE
Support rds for postgres

### PR DESCRIPTION
**Pull request by fhanson**
Add support for remote databases using updated resources in https://github.com/opscode-cookbooks/enterprise-chef-common/pull/35
https://github.com/chef/supermarket/issues/1053

### CODE REVIEW

**Comment by nellshamrell** [comment]
LGTM

**Comment by fhanson** [comment]
Will need changes based on the changes that get pulled into enterprise-chef-common. Waiting to hear about the resources pg_user and pg_database

**Comment by smith** [comment]
Uploaded a [0.6.0 of enterprise](https://github.com/opscode-cookbooks/enterprise-chef-common/releases/tag/0.6.0). An update to the [Berksfile](https://github.com/chef/omnibus-supermarket/blob/master/cookbooks/omnibus-supermarket/Berksfile), a `berks update enterprise`, and committing the changed Berksfile and Berksfile.lock will be needed.

**Comment by fhanson** [comment]
@smith updates to berksfile and .lock are in place and the pg_user and pg_database resources have been updated to include the connection info if postgresql is not enabled.

**Comment by smith** [comment]
:+1:

**Pull request merged**
